---
# handlers file for zabbix-agent

- name: Install agent repo
  apt:
    deb: "{{ zabbix_deb }}"

- name: Update repo
  apt:
    update_cache: yes

- name: Install Zabbix-Agent v5.0.16
  package:
    name: zabbix-agent
    state: present

- name: Copy template
  template:
    src: zabbix_agentd.conf.j2
    dest: "{{ zabbix_agent_conf_dest }}/zabbix_agentd.conf"
    owner: root
    group: root
    mode: '0644'

- name: Restart service
  service:
    name: zabbix-agent
    state: restarted
    enabled: yes
