---
# defaults file for pgbouncer-config
pgbouncer_startup_parameters_regex: '^ignore_startup_parameters = extra_float_digits,geqo'
pgbouncer_startup_parameters: 'ignore_startup_parameters = extra_float_digits,geqo,options,search_path,replication'
